image: patrickmckernin/msm-signin-2022-spring

tasks:
  - init: pip3 install -r requirements.txt
    command: python3 src/app.py

  - before: |
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9500-9999
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify

